SignalK/SensESP

- platformio.ini
- src/devices/onewire_temperature.cpp
- src/devices/onewire_temperature.h
I had broken Onewire device detection logic, and the debug messages were misleading as well.
> fix: Onewire detection logic

- src/sensors/onewire_temperature.cpp
A recently modified debug() message broke the build.
> fix: change config_path to config_path.c_str() in debug msg

- src/net/ws_client.cpp
- src/signalk/signalk_output.h
- src/system/nmea_parser.cpp
Due to a missing `break`, `PSTI,032` (RTK baseline data) values were never properly emitted. Also the reported date was 100 years off.
> fix: PSTI,032 NMEA message bugfixes

- src/sensors/analog_input.cpp
- src/sensors/analog_input.h
- src/sensors/digital_input.cpp
- src/sensors/gps.cpp
- src/sensors/onewire_temperature.cpp
- src/sensors/sensor.cpp
- src/sensors/system_info.h
- src/signalk/signalk_output.h
- src/system/enable.cpp
- src/system/enable.h
- src/transforms/analogvoltage.h
- src/transforms/angle_correction.cpp
- src/transforms/curveinterpolator.cpp
- src/transforms/debounce.cpp
- src/transforms/difference.cpp
- src/transforms/frequency.cpp
- src/transforms/integrator.cpp
- src/transforms/linear.cpp
- src/transforms/moving_average.cpp
- src/transforms/timestring.cpp
- src/transforms/transform.cpp
- src/transforms/transform.h
- src/transforms/voltagedividerR2.cpp
Add more detailed info to the startup messages in the Serial Monitor, showing each sensor and transport that's being enabled. Output looks like this. I don't know what the leading integer is, nor the trailing "fE" and "E" in some cases. That's what comes back from `return typeid(*this).name();`
```␛[0m(I) (enable) WS client enabled
␛[0m(D) (enableAll) Enabling sensor or transform: 6Linear
␛[0m(D) (enableAll) Enabling sensor or transform: 22TemperatureInterpreter
␛[0m(D) (enableAll) Enabling sensor or transform: 16VoltageDividerR2
␛[0m(D) (enableAll) Enabling sensor or transform: 8SKOutputIfE
␛[0m(D) (enableAll) Enabling sensor or transform: 13AnalogVoltage
␛[0m(D) (enableAll) Enabling sensor or transform: 11AnalogInput
␛[0m(D) (enableAll) Enabling sensor or transform: 8SKOutputI6StringE …
```
> feature: add Enable::getClassName, use it in EnableAll()

- src/net/networking.cpp
- src/net/networking.h
- src/sensors/onewire_temperature.cpp
- src/wiring_helpers.cpp
With this one, I'd like you to think hard whether you like my approach. Basically, I found that the bug @ba58smith reported was almost a show-stopper for me. I had some sensors behind the same power switch as the SK server itself. When I turned the power on, the Raspi couldn't get the network up fast enough and the ESPs would fall back to unconfigured mode. Every single time.
What I do is I save SSIDs and network passwords after a successful network login via Wifimanager. Then, if the values have been set, they're used unconditionally for reconnecting to the network. Basically, once Wifimanager is successfully used, the next time the device will wait forever until the same network becomes available again. The downside is there's no way to access Wifimanager again but by resetting the …
> fix: Hard-code network settings after one successful connection

- src/transforms/moving_average.cpp
- src/transforms/moving_average.h
Reviewing @joelkoz's recent change to MovingAverage, I realized I didn't understand how it worked. The PR adds a description for the class documentation, and explains how the transform works.
> Add comments for documentation

- src/sensors/gps.cpp
- src/system/nmea_parser.cpp
- src/wiring_helpers.cpp
- src/wiring_helpers.h
The NS-HP-GN GPS modules didn't seem to boot reliably after power-up, so I added some code to reset them after the startup.
Also: properly set all time struct fields when decoding GPS messages.
Also also: return the GPSInput object so that the wiring can be amended afterwards.
> Reset GPS after boot

- examples/gps_compass.cpp
- src/sensors/gps.cpp
- src/sensors/gps.h
- src/system/nmea_parser.cpp
- src/system/nmea_parser.h
- src/wiring_helpers.cpp
- src/wiring_helpers.h
NMEA Input streams are now configurable and the software serial library can be used to handle the serial receive pin.
Also removed the resetting logic because it was very specific to my own setup and shouldn't have been added to SensESP in the first place.
> Configurable NMEA input stream

- src/net/ws_client.cpp
During authorization of the token, the SignalK server sometimes returns an empty payload
> FIX: protection fault on startup during authorization

- src/signalk/signalk_delta.cpp
This PR logs the SK deltas emitted by the sensor to the debug output. Seeing how often we are sending deltas can be quite enlightening as its easy to overwhelm the server with unchanged values.
> ENH: Log emitted SignalK deltas to debug stream

- src/transforms/change_filter.cpp
Noticed this while looking at the contstructors of all configurable classes for `load_configuration()`.
> Add classname to change_filter()

- src/transforms/moving_average.cpp
The moving_average transport didn't show its last value when looking at its configuration data. I've found it helpful to have that when troubleshooting output, so I added it.
> Add 'last value' to moving_avg config data

- src/sensesp_app.cpp
- src/sensesp_app.h
- src/system/configurable.cpp
Make the debug message for `Configurable::load_configuration()` specific to the cause of the message (no config path was specified, or no file was found in SPIFFS).
I did this because I often saw one or the other of these messages in the Serial Monitor that didn't make sense, so I wanted to make sure I understood the message. Now that I've done that, I've uncovered what I think is a bug: the error message that results from `if (!SPIFFS.exists(config_path))` happens for many sensors and transports when it doesn't appear to be correct. See Issue #88 .
> Configpath msgs

- examples/analog_input.cpp
Use new version of AnalogInput sensor that takes a configurable read_delay value.
Update the example to make it more like all the other examples with respect to the "wiring", and the config paths for everything. Expand the comments.
> Update AnalogInput example

- examples/OneWire_temperatures.cpp
- src/sensors/onewire_temperature.cpp
- src/sensors/onewire_temperature.h
Add `uint read_delay` to the constructor of OneWireTemperature, with the default value of 1,000, which is what it was hard-coded to be before this.
Confirmed (on my own boat with OneWire sensors) that the read delay can be set separately for each sensor.
I wanted to add this to the configurable values, but I get a JSON error whenever I try to access the configuration through the web UI. Something about not being able to read the configuration. "Unexpected token t at position 405'. 
This will break any existing main.cpp that uses OneWire, IF a config path was specified for `OneWireTemperature`, like this:
`new OneWireTemperature(dts, "/coolantTemperature/oneWire");`.
Should not be a problem - just add the desired read_delay:
```
uint read_delay = 500;
new OneWireTemperature(dts, …
```
> Add read_delay to onewire_temp sensor

- examples/analog_input.cpp
- src/sensesp_app.h
- src/wiring_helpers.cpp
- src/wiring_helpers.h
See Issue #99 . Also, change some variable names in the fuel flow meter example to make them a little more instructional for a new user.
> Remove 'sensors' from all SK Paths

- examples/bme280_example.cpp
- platformio.ini
- src/sensors/bme280.cpp
- src/sensors/bme280.h
Per a request from someone on Slack. Issue #96 .
> Add BME280 sensor with example

- platformio.ini
- src/sensors/bmp280.cpp
- src/sensors/bmp280.h
Per a request from somone on Slack, after I said I'd do the BME280. Issue #94 .
> Add BMP280 sensor

- examples/sht31_example.cpp
- platformio.ini
- src/sensors/sht31.cpp
- src/sensors/sht31.h
Someone on Slack asked for it. Issue #98 .
> Add SHT31 temp/humidity sensor

- platformio.ini
The Adafruit INA219 Library was missing from the dependency list causing the examples to compile with an error. This fixed it for me. I just started learning about SensESP, so I'm not sure it's the only place to edit...
> Add Adafruit INA219 Library

- README.md
- examples/relay_control.cpp
- src/net/ws_client.cpp
- src/net/ws_client.h
- src/sensors/digital_output.cpp
- src/sensors/digital_output.h
- src/signalk/signalk_listener.cpp
- src/signalk/signalk_listener.h
- src/signalk/signalk_value_listener.h
- src/transforms/threshold.cpp
- src/transforms/threshold.h
Added support for listening SignalK paths using SignalK subscription over WS. 
Added few classes to support subscribing to data on server. 
I've created class that represents value listerner called **SKValueListerner<T>**, that is **ValueProducer<T>**, so using what is already there I can connect value in SignalK to for example **DigitalOutput** (new class added). 
This is sample code for connecting navigation.lights value to D1 digital output for switching relay:
```
auto * listener = new SKValueListener<bool>("navigation.lights", 500);
listener->attach([]()
{
debugI("Navigation lights status has been updated!");
});
listener->connectTo(new DigitalOutput(5));
```
I've tested this code using D1 mini with relay HAT and SignalK Node Server and it works just fine.
> Add SKValueListener and DigitalOutput

- library.json
- src/net/networking.cpp
- src/net/ws_client.cpp
- src/sensesp_app.cpp
- src/sensors/system_info.cpp
- src/system/configurable.cpp
- src/system/spiffs_storage.cpp
- src/transforms/change_filter.cpp
- src/transforms/median.cpp
I was working in parallel to @loopsmark on ESP32 support. The code changes are very similar, but i still post my work, since it differs in two import points:
* I use ESPTrueRandom for ESP8266 and ESP32, which simplifies the library dependencies.
* It is possible to import SensESP as a library in a project without any other dependencies.
As an example you can look at https://github.com/gzahl/SensGPS, which compiles for ESP8226 and ESP32 from the same sources. Both only depend explicitly on https://github.com/gzahl/SensESP#esp32
Please feel free to pull either my work or @loopsmark work. But it would be really nice to be able to simply import the upstream version of SensESP into new projects.
On a sidenode: 
* The dependency system of platformio is a mess (or i still don't understand it). …
> ESP32 support and easy import as library

- src/net/networking.cpp
This should fix issue #87. When ESP is connecting to known WiFi SSID, then mode is changed to WIFI_STA instead of leaving it on WIFI_AP_STA.
> fix: change to WIFI_STA mode when connected to known WiFi

- src/net/networking.cpp
This message was the opposite of what it should have been. It really means "Using SSID and password that were saved by WifiManager or updated in the Config UI" - but that seems a bit much, so I just made it "Using saved SSID and password".
> Correct erroneous Debug message

- src/net/networking.cpp
- src/sensesp_app.h
Hostname can now be set and edited independently of wifi credentials. That is, either or both can be set or not set with SensESPAppBuilder in main.cpp, and still behave properly in the Config UI.
> Fix problem with hostname in Issue #144

- library.json
Projects using SensESP won't build properly because PIO 5.0.1 fails
to detect some dependencies of some Adafruit sensor libraries. As
a workaround, declaring these two dependencies in library.json seems
to fix.
This commit should be reverted once the underlying issue has been fixed.
> Add indirect dependencies as a workaround to a PlatformIO 5.0.1 bug

- examples/OneWire_temperatures.cpp
- examples/ads1x15_volt_meter.cpp
- examples/analog_input.cpp
- examples/bme280_example.cpp
- examples/bmp280_example.cpp
- examples/fuel_flow_meter.cpp
- examples/fuel_level_sensor/main.cpp
- examples/gps_compass.cpp
- examples/ina219_example.cpp
- examples/platformio.ini
- examples/relay_control.cpp
- examples/rpm_counter.cpp
- examples/sht31_example.cpp
- examples/temperature_sender.cpp
- examples/thermocouple_temperature_sensor/max31856TC_example.cpp
- examples/ultrasonic_level_sensor/ultrasonic_DVP_example.cpp
- platformio.ini
Provide a sample `platformio.ini` file in `examples`. Also reformat and standardize variable naming for all examples.
> Sample platformio.ini

- platformio.ini
This is required to build SensESP locally.
> platformio.ini should no longer peg ArduinoJson to v5

- examples/platformio.ini
I had accidentally enabled more than one environment in the example platformio.ini file, which probably was counterproductive. Fixed now. Also added commented out sections for setting upload ports and the builtin led in ESP32.
> Example platformio.ini environments

- src/sensors/analog_input.cpp
- src/sensors/analog_input.h
- src/sensors/analog_reader.h
This class implements ESP32 support for AnalogInput. Some sensible defaults are used at the moment for attenuation and bit width values.
Tested both on ESP8266 and ESP32.
> ESP32 support for AnalogInput

- library.json
This is to fix the first compiler warning identified in Issue #179.
> Specify the correct OneWire library

- src/net/ws_client.cpp
- src/net/ws_client.h
Discussed w/ @mairas - we're not sure what the `WiFiClient client` does, but it allows the use of the current `HTTPClient::begin()`, and gets rid of the compiler warning about using a deprecated version (Issue #179). 
Tested with ESP8266 and ESP32 - data flows all the way to the SK Server, so it seems to work as it did before.
> Stop using deprecated HTTPClient::begin(String)

- examples/bme280_example.cpp
There was a missing / in config path for humidity value.
> Fix bme280 config path

- src/sensesp_app.cpp
- src/sensesp_app.h
Fixed a compile error: SetupSerialDebug was defined in the .hpp file, while it should've been just declared there and defined in the .cpp. file.
> Define SetupSerialDebug in a cpp file

- examples/lambda_transform.cpp
- src/transforms/lambda_transform.h
Lambda Transform is a transform that can be defined using a transform function, without having to create a new transform class for each new transform. The transforms also allow for defining a number of configuration parameters that can be modified using the web interface.
The implementation could be cleaner: in particular, variadic template parameters could be used to remove pretty much all code duplication related to differing parameter list lengths. However, the current version of the GCC compiler provided by the Arduino Framework exposes a bug which I couldn't work around. Changing the implementation later wouldn't affect the public interface, though.
> Lambda Transform

- src/sensors/ultrasonic_distance.h
featherexp32 would not compile without this change although the other environments had no problems.
I also had to add the line extends = expressif32_base to the environment section for featheresp32 as it was generated by the "New Project" procedure in platformIO. If this wasnot done, the memory image for the featheresp32 environment was too large and generated an error.
Should this be noted in the instructions?
> Moved uint read_delay to private and below the declarations for other parameters.

- src/sensors/ads1x15.h
- src/sensors/bme280.h
- src/sensors/bmp280.h
- src/sensors/ina219.h
- src/sensors/sht31.h
- src/sensors/ultrasonic_distance.h
- src/system/enable.h
- src/system/valueconsumer.h
- src/system/valueproducer.h
- src/transforms/curveinterpolator.h
This PR takes care of a lot of compiler warnings.
Commenting code out should generally be avoided but I resorted to that with a clear FIXME message to indicate that those lines should be restored once the toolchain allows that.
> Stop using [[deprecated]] attributes due to too old GCC

- src/sensesp_app.h
- src/sensors/bme280.h
- src/sensors/ina219.h
Some member variables had still the Hungarian notation pointer prefixes. Removed in this PR.
> Fix some variable names that dodged the first round

- src/transforms/lambda_transform.cpp
- src/transforms/lambda_transform.h
- src/transforms/linear.cpp
- src/transforms/linear.h
This is a reimplementation of the `Linear` transform class, illustrating the potential benefits of implementing the basic transforms using `LambdaTransform`.
The first commit is a bugfix for `LambdaTransform` implementation. If desired, I can make it a separate PR but this Linear transform reimplementation depends on it.
> Linear transform reimplemented as a LambdaTransform

- examples/platformio.ini
- library.json
- platformio.ini
Some dependencies were missing from the previous magnetometer PR and new builds broke due to that. This PR fixes that. Unfortunately, PlatformIO's Library Dependency Finder (LDF) is no longer able to find all dependencies with the default settings, so changes to `platformio.ini` are required.
> Missing magnetometer dependencies

- .github/workflows/test.yml
- src/transforms/hysteresis.h
There is a difference between ESP8266 and ESP32
SDK gcc compilers in how the template class base class constructor
calls work. The original code wouldn't work on ESP8266 (gcc 4.8.2)
but did work on ESP32 (gcc 5.2.0). Pulling the array out of the
class makes it work for both.
Fixes #222.
> Hysteresis: Move the param_info array out of the inherited class

- src/net/ws_client.cpp
Trying to pinpoint the reason for the failure of an approved Security Token. (Issue #213 )
> Add type of DeserializationError to Serial output

- src/net/discovery.cpp
ESP32 SensESP is not using hostname for mDNS name at the moment. This fix the issue and show correctly user defined hostname also in mDNS name.
> fix: ESP32 hostname for mDNS name

- src/sensors/digital_input.cpp
While testing another PR, I noticed this issue. It goes back to PR #125, when DigitalInputValue was first made configurable by the addition of read_delay, but load_configuration() wasn't added to the constructor at that time.
> Add load_configuration() to DigitalInputValue constructor

- examples/platformio.ini
Addresses Issue #156 .
After making this change in my project's platformio.ini, I erased the flash on my ESP8266 (D1 Mini) and reloaded. Then I brought up the Config UI and changed a couple of the configurable items in my project and saved them. Restarted the ESP and checked the Config UI to confirm my changes had been saved. Then I changed them back, restarted the ESP again, and made sure those changes had been saved. Everything worked as expected.
> Replace deprecated build flag

- src/sensors/analog_input.cpp
- src/sensors/bme280.cpp
- src/sensors/bmp280.cpp
- src/sensors/digital_input.cpp
- src/sensors/max31856_thermocouple.cpp
- src/sensors/onewire_temperature.cpp
- src/sensors/sht31.cpp
- src/sensors/system_info.cpp
- src/sensors/ultrasonic_distance.cpp
- src/signalk/signalk_output.h
- src/signalk/signalk_value_listener.h
- src/system/observablevalue.h
- src/system/valueproducer.h
- src/transforms/analogvoltage.cpp
- src/transforms/angle_correction.cpp
- src/transforms/change_filter.cpp
- src/transforms/debounce.cpp
- src/transforms/difference.cpp
- src/transforms/frequency.cpp
- src/transforms/integrator.cpp
- src/transforms/integrator.h
- src/transforms/timestring.cpp
- src/transforms/voltage_multiplier.cpp
- src/transforms/voltagedivider.cpp
Most sensors keep repeating the following pattern:
output = some_value;
notify();
This PR implements `ValueProducer::emit(value)` that changes the pattern to the following:
this->emit(some_value);
> ValueProducer::emit(value)

- src/net/ws_client.cpp
- src/net/ws_client.h
- src/sensesp_app.cpp
- src/sensesp_app.h
- src/sensesp_app_builder.h
Hi Guys,
I've implemented sending permissions in token request to SignalK server - tested with readwrite (default) permission and also with admin permission. Solves issue #173 
I've changed set_sk_server method on Builder and added third parameter permission with default READWRITE value. I've have changed SensESPApp ctor paramteters to add permision. Same with WSClient.
Let me know what you think!
Jan
> Allow device to fill in requested permissions in token request to server

- src/net/networking.cpp
- src/net/networking.h
- src/net/ws_client.cpp
- src/net/ws_client.h
- src/sensesp_app.cpp
- src/system/led_blinker.cpp
- src/system/led_blinker.h
- src/system/observablevalue.h
Previously, Networking and WSClient objects reported their state using callbacks which wasn't in line with the rest of the architecture and was also quite limiting in what you could do.
Now, Networking and WSClient are both ValueProducers that notify their consumers of state changes. LedBlinker is one such consumer.
This change in itself is not a very significant one but paves way for refactoring the LedBlinker class and also, with a bit of further refactoring, allows for example for having the device state to be displayed on a small I2C OLED display.
> Networking and WSClient objects report their state via ValueProducers

- src/sensors/sensor_nxp_fxos8700_fxas21002.cpp
- src/sensors/sensor_nxp_fxos8700_fxas21002.h
Issue #151 dealt with a failed BME280 sensor causing the system to fail to start. A similar situation exists with the NXP FXOS8700 / FXAS21002 combination orientation sensor: if I2C communications with the sensor fails, the system hangs. It is preferred that the SensESP program continues to run, to avoid halting data from possible other attached sensors.
Only two files have changed: `sensor_NXP_FXOS8700_FXAS21002.h` and `sensor_NXP_FXOS8700_FXAS21002.cpp`
* `SensorNXP_FXOS8700_FXAS21002::connect()` changed so failure to init calibration helper (which retrieves cal values stored in EEPROM) does not halt program, but rather allows it to continue with warnings displayed on serial console.
* `SensorNXP_FXOS8700_FXAS21002::initSensors() now checks to see whether communications with the sensor …
> Failed orientation sensor communication no longer hangs/reboots system

- examples/hysteresis.cpp
- examples/lambda_transform.cpp
- src/sensesp_app.cpp
- src/sensesp_app.h
- src/sensesp_app_builder.h
The SensESPApp constructor had a rather long argument list, with most arguments being rather inessential. This wasn't great as a public interface and would've caused future refactoring of the arguments always break the public interface.
This change is required to limit the growth of the constructor argument list length, to maintain separation of public and non-public interfaces and to only have the essential arguments in the public constructor.
> Split SensESPApp initialization to separate constructor and setup calls

- src/sensors/sensor_nxp_fxos8700_fxas21002.cpp
- src/sensors/sensor_nxp_fxos8700_fxas21002.h
The default fusion filter selected in the orientation sensor files has been changed from Adafruit_NXPSensorFusion (which was global) to Adafruit_Mahony (which is part of the class). This can save runtime RAM in cases where SensESP is not using the orientation sensor yet the orientation code is linked in anyway. Testing suggests this doesn't happen on ESP32 boards but may on ESP8266.
> Changed to a non-global fusion filter

- src/transforms/integrator.cpp
- src/transforms/integrator.h
Fixed a bug in the Integrator Transform - it didn't use the multiplier (`k`) in the calculation of `value`.
Added a public method to reset `value` to 0. Will be used in conjuction with a new LambdaConsumer to reset the value when the user does something (pushes a button, for example).
> Fixed a bug in Integrator Transform; gave it a reset() method

- examples/fx8700_heading_example.cpp
- src/sensors/orientation_9dof_input.cpp
- src/sensors/orientation_9dof_input.h
- src/sensors/sensor_nxp_fxos8700_fxas21002.cpp
- src/sensors/sensor_nxp_fxos8700_fxas21002.h
Issue #239 and @joelkoz (https://github.com/SignalK/SensESP/issues/239#issuecomment-724183941) suggested an additional improvement to the orientation code. The pointer, which was global, to the dynamically-allocated `sensor_fxos_fxas` has been moved into the class `Orientation9DOF`. 
During testing this change, I also discovered how to move the object `Adafruit_NXPSensorFusion filter` inside the class. That filter (the subject of PR #247) had been global as otherwise the filter didn't function. This filter is now defined in 'sensor_nxp_fx8700_fxas21002.h` together with the two other filters that had not had this limitation.
This PR edits `fx8700_heading_example.cpp` and the four orientation source files.
> Remove global pointer from Orientation source

- src/sensors/ultrasonic_distance.cpp
The code will hang with a Security Token loop when the sensor is not connected if this delay is not present.
> Add a 50 ms timeout to the pulseIn(...) statement.

- src/sensors/sensor_nxp_fxos8700_fxas21002.cpp
Issue #256 noted that the `begin()` method of the Wire library differs between the ESP8266 and ESP32 versions. This PR removes the frequency from the begin() call, and instead makes a separate call to `setClock()`  The code is now compatible with both versions of the Wire library and fixes #256.
I've verified that it compiles without warnings for the d1_mini and ESP32-Wrover, and runs on the Wrover. I don't have a board to test the d1_mini executable (but have one ordered).
> Split frequency from Wire.begin() for ESP8266 compatibility

- src/net/ws_client.cpp
- src/signalk/signalk_put_request_listener.cpp
- src/signalk/signalk_put_request_listener.h
A ValueProducer that listens to incomming PUT requests. This was required because the Signal K spec requires devices that publish paths and expect to be manipulated via PUT requests need to respond to a websocket broadcast different from an "update" from a subscription, aas well as send a response
> Initial version of SkPutRequestListener<>

- library.json
- platformio.ini
EspSoftwareSerial should only be explicitly included when compiling for ESP32
> Fix EspSoftwareSerial compile error

- src/transforms/repeat_report.cpp
- src/transforms/repeat_report.h
RepeatReport() is a transform for values that do not change frequently, but to still ensure they can be reported to another consumer (like the SK server) at frequent intervals.
> Added RepeatReport<> transform

- examples/ads1x15_volt_meter.cpp
- src/sensors/ads1x15.cpp
- src/sensors/ads1x15.h
- src/transforms/ads1x15_voltage.h
Addresses the items in Issue #242.
The new ADS1x15Voltage is identical to the class it inherits from, ADS1x15RawValue, except for one additional computation. It works as intended, but I'm not sure if the configuration methods will work the way I've done it (i.e., not defining the configuration methods in the new class). And I don't have an ADS1115 to test it with for another couple of weeks. So please give that aspect of it a good look.
> Ads1x15 fix and enhancement

- src/sensors/digital_output.cpp
- src/sensors/digital_output.h
DigitalOutput was originally designed as a ValueConsumer<bool>.  This minor refactor changes it to a BooleanTransform that passes the input value along after setting the pin, allowing for its use in more complicated wiring designs.
> Refactored DigitalOutput to pass through input values

- src/transforms/truth_text.cpp
- src/transforms/truth_text.h
This is the remnants of the "LoadController and Truth" PR, which now contains only the TextToTruth() and TruthToText() transforms.  LoadController is no longer needed if DigitalOutput is refactored to be a BooleanTransform
> TextToTruth transform

- src/transforms/click_type.cpp
- src/transforms/click_type.h
This is a refactor of the ClickType class. 
Changes based on our discussions:
1. ButtonPress and ButtonRelease ClickTypes have been added and are reported appropriately
2. The big convoluted IF statement from `set_input()` has been broken up into smaller functional methods for clarity
3. All protected state member variables have been documented for Doxygen.  Many have been renamed to clarify their use
4. elapsedMillis class library was used for timing routines.  Two member values that saved the current millis() value has been refactored to be elapsedMillis types
I did not use a state machine because really there are only two states: "idle" (`click_count == 0`) and "click in progress" (`click_count >= 1`).  The old code did use some implied values on the timer values to determine state, so …
> ClickType Transform

- src/transforms/press_repeater.cpp
- src/transforms/press_repeater.h
This is the main functionality of the old Button class, refactored to drop the digital input functionality and wrap the behavior in a BooleanTransform.
I opted to name this PressRepeater because upon further reflection, the suggested DigitalInputRepeater was too specific. While wiring this up to a digital input is by far the most common use case, I could see the need to use a different input, such as the boolean value coming in from a PUT request listener. That name may have made sense if we kept the "digital input" functionality in it, but as of now, this is a simple, generic transform.
> PressRepeater transform

- src/system/pwm_output.cpp
- src/system/pwm_output.h
Provides a platform independent mechanism for managing "pwm channels" on both esp8266 and esp32.  Outputs can be written via static class methods or with an instance of PWMOutput (which is a ValueConsumer<float>)
> PWMOutput class for platform independent pwm outputs

- examples/gps_compass.cpp
- library.json
- platformio.ini
As discussed in #283, this PR removes the EspSoftwareSerial PR altogether. I refactored the gps_compass example to use SoftwareSerial (which is provided by the Arduino SDK) on ESP8266 and another HardwareSerial UART on ESP32. The resulting #ifdefs are a bit messy but at least the dependency could be removed for good.
Fixes #262.
> Remove EspSoftwareSerial dependency

- src/sensors/analog_input.h
There was a lack of understanding of the purpose of the `output_scale` member of the AnalogInput class. These additional comments will hopefully resolve that.
> Expand the output_scale comment

- src/transforms/hysteresis.h
- src/transforms/lambda_transform.h
The previous version of `Hysteresis` used a static member variable to store the output state, potentially breaking the transform if it was instantiated more than once (as the different instances would store the same state). Now state is a regular member variable.
I had to change `LambdaTransform` to use `std::function` instead of old-fashioned function pointers. That likely incurred a small performance penalty when calling the lambda function but I think code readability is now slightly better.
Fixes #250.
> Hysteresis transform can be instantiated many times

- platformio.ini
Addresses Issue #278 .
Fixed the same way as it was fixed in the example platformio.ini file: PR #228 .
> Fix deprecated build flag for configuring flash

- src/sensors/digital_input.cpp
- src/sensors/digital_input.h
Update comments to Doxygen style.
Change DigitalInputValue to DigitalInputState.
Properly initialize `triggered` variable.
Remove `value` from showing in the Config UI.
Add new class: DigitalInputChange.
Fix class member variable names.
> DigitalInput fixes and updates

- .github/workflows/test.yml
- ci/README.md
- ci/platformio-d1_mini.ini
- ci/platformio-esp32dev.ini
- ci/run-ci.sh
I began tweaking our `.github/workflows/test.yml` file to enable testing on esp32 as well but then realized that we _are_ building against that, too. Similarly to running `pio run` on the command line, it builds all default environments. It's not terribly visible in the CI details because the esp32 build is after the super-long esp8266 build log, but it is there nevertheless.
So instead of doing anything for that, I limited the number of examples to be built to make the build a bit faster. I removed examples that I thought didn't test any new features. Or at least that was the intention...
Fixes #288. (Actually it wasn't broken to begin with.)
> Limit the number of examples to be built in CI

- src/net/http.cpp
As reported by @KEGustafsson :
The web config UI wouldn't work with more than six sensors. The
culprit was found to be the output buffer size. It's now increased
to 4096 on ESP32. On ESP8266 memory is at premium and the amount
of sensors likely less anyway, so there the buffer size was left at
1024.
> Increase output buffer size on ESP32

- src/system/observable.cpp
- src/system/observable.h
Observable needed an explicit move constructor to prevent this warning:
```
warning: defaulted move assignment calls a non-trivial move assignment operator for 
virtual base virtual-move-assign
```
> Fixed compiler warning re: non-trivial Observable move

- src/sensors/digital_input.cpp
- src/sensors/digital_input.h
The output is compared to the previous output, and if it's not different, it's not emitted. This caused the intial value to not be output, if the first value was 0 (button goes to GND when pressed). Now the initial value will always be output.
> DigitalInputChange: always output first value

- src/transforms/debounce.cpp
- src/transforms/debounce.h
The logic for the Debounce Transform wasn't really doing a debounce. Now it is.
Also made it a Template class to handle all types of input.
Also made the debounce delay configurable.
Also updated the comments to Doxygen style.
(Oops - I guess this should have been four different commits. Sorry!)
> Change debounce logic

- src/net/ws_client.cpp
- src/net/ws_client.h
This fix is for the loss of device authentication when the SignalK server or network goes down AFTER the initial authentication check. SensESP would clear the token and request a new one in this scenario.  Fixes #213 
Source code provided by @JohnySeven
> Fix #213 Access Token Lost on network problem

- src/net/ws_client.cpp
- src/net/ws_client.h
- src/sensesp_app_builder.h
This is the fix for #314. It has, by default, the authorization token retested each time the device connects to the Signal K server.  This feature can be turned OFF for limited power situations (like smart watches) by calling the `SensESPAppBuilde`r's new `set_test_auth_on_each_connect()`, or by setting the global static `WSClient::test_auth_on_each_connect_` member.
> Configurable test of auth token on each connect

- examples/ads1x15_volt_meter.cpp
- src/signalk/signalk_output.cpp
- src/signalk/signalk_output.h
This PR adds a warning when outputting numeric values without metadata.  Also, an additional (optional) constructor parameter has been added to allow a quick specification of the "units" field by using a String as the third parameter.
This was from an idea sparked from discussions in #323
> Easy units and meta warnings for numeric SK outputs

- src/signalk/signalk_metadata.cpp
- src/signalk/signalk_metadata.h
This field should be a `float`.  Our default value of -1 means the timeout is not specified (so it won't be explicitly sent, and will use the server's default).
> SKMetadata timeout is a float

- src/signalk/signalk_delta.cpp
- src/signalk/signalk_delta.h
The delta output serialization buffer was fixed to 1024 characters. That wouldn't be enough if there're many paths or metadata to transmit.
This PR adds some crummy heuristics for estimating the required buffer size based on the data to be transmitted. An added benefit is somewhat smaller buffers for simple programs.
> Estimate the required delta serialization buffer size based on data

- examples/bmp280_example.cpp
- src/sensors/bmp280.cpp
- src/sensors/bmp280.h
Someone needed to be able to use the TwoWire I2C interface, which required a different constructor.
Cleaned up comments and member variable names, and remove "value" from the display in the Config UI to be consistent with changes we've been making to other classes.
> BMP280 - overload the constructor, code cleanup

- src/sensors/bme280.cpp
- src/sensors/bme280.h
- src/sensors/digital_output.cpp
- src/sensors/digital_output.h
- src/sensors/gps.cpp
- src/sensors/gps.h
- src/sensors/ina219.cpp
- src/sensors/ina219.h
- src/sensors/onewire_temperature.cpp
- src/sensors/onewire_temperature.h
- src/wiring_helpers.cpp
Going through all the Sensor files to make sure they:
- Have Doxygen-style comments
- Have data member names with trailing "_"
- Don't have "value" as a read-only entry in the Config UI
~~This is enough for one PR. I'll keep going in other PR's.~~
Oh, what the heck. I'll do another one or two in this PR.
OK, NOW this is ready for review. Lots of commits, all of them very small and "focused" - should be easy to review.
> Doxygen, fix data member names, remove "value" from Config UI for many Sensors

- src/transforms/angle_correction.cpp
I missed this in my cleanup of all the transforms.
> AngleCorrection: remove value from config display

- examples/platformio.ini
Add `https://github.com/SignalK/SensESP` to the `lib_deps = ` section of `examples/platformio.ini`, as an option to `SignalK/SensESP`, because the latter doesn't have any of the PR's merged since the last release.
This is the result of spending a lot of time helping figure out why new users are getting errors - because they're using new examples from `master`, with code from `latest` (the current "Relase" version).
Hopefully, this will cut down on support issues, or at least make it easier to tell someone how to solve the "using new examples" problem.
> Clarify which SensESP to use in platformio.ini

- src/sensors/onewire_temperature.cpp
- src/sensors/onewire_temperature.h
I took the easy way out (instead of trying to manage it with concurrent programming - after the warning by @mairas ).
> Fix: 1Wire read delay needs to be longer than the conversion delay

- src/sensors/ads1x15.cpp
- src/sensors/ads1x15.h
- src/sensors/bme280.cpp
- src/sensors/bme280.h
- src/sensors/bmp280.cpp
- src/sensors/bmp280.h
- src/sensors/orientation_9dof_input.cpp
- src/sensors/orientation_9dof_input.h
- src/sensors/sht31.cpp
- src/sensors/sht31.h
This goes back to the first sensor code that I wrote. I mistakenly made the class that represents the physical sensor inherit from `Sensor`. It doesn't need to, because it doesn't have anything that's configurable, and it doesn't actually emit anything.
- ADS1x15
- BME280
- BMP280
- SHT31
- 9DOF
> FIX: Many "sensor" classes should not inherit from Sensor

- examples/hysteresis.cpp
- examples/lambda_transform.cpp
- examples/smart_switch/remote_switch_example.cpp
- examples/smart_switch/smart_switch_example.cpp
- examples/temperature_sender.cpp
Recently had a new user who didn't recognize `sk-server.local` as an alias for the SK Server's IP address, and I spent a couple hours helping him track it down. I'm assuming most users will recognize an IP address as something they need to change, like their wifi SSID and password.
> Use an IP address for all server addresses in /examples

- examples/smart_switch/remote_switch_example.cpp
- src/controllers/smart_switch_controller.cpp
- src/controllers/smart_switch_controller.h
- src/signalk/signalk_put_request.cpp
- src/signalk/signalk_put_request.h
Fixes the strange timing problem when a PUT request is issued by a remote switch, but the the physical switch controller sends its current status before it answers the PUT request. This caused the remote switch to issue a second PUT request as it appeared the state had changed yet again.
This fix will also prevent future issues with the server being overwhelmed with requests as this only lets any one PUT request instance to make a single request at a time.
> Prevent duplicate PUT requests

- src/transforms/repeat_report.cpp
- src/transforms/repeat_report.h
Now, if you set the "repeat interval" to zero via the configuration UI, the auto-repeating of the value is disabled.
> Added option to disable RepeatReport repeating

- src/transforms/transform.h
@param `id` was replaced by `config_path` a long time ago.
> Fix outdated comment in Transform.h

- src/sensesp_app.cpp
- src/sensors/system_info.cpp
Basically, we are unable to turn off the debug*() informative prints due to two small compilation errors. Corrected by including one #ifndef guard and one #include statement.  See #358 for details.
This resolves #358.
> Allow compilation when DEBUG_DISABLED defined

- src/signalk/signalk_delta.cpp
When working with the Json doc size estimates, it seems I left behind an unnecessary and spammy debugging message.
> Remove the delta size estimate debugging message

- src/controllers/smart_switch_controller.cpp
- src/controllers/smart_switch_controller.h
This PR enhances SmartSwitchController to allow the "double click" button input to sync the light's status to one or more additional sk paths via an SKBooleanPutRequest().  For example, a "double click" on one of the boat's interior lights can cause ALL the interior lights to turn on.
> ENH: SmartSwitchController double click to sync sk paths

- src/controllers/system_status_controller.cpp
- src/controllers/system_status_controller.h
- src/net/networking.cpp
- src/net/networking.h
- src/sensesp_app.cpp
This PR implements quite a few changes in the networking code. WiFi connection logic is no longer blocking: we don't need to wait for the wifi to get connected before entering the main loop. This allows easier simultaneous NMEA 2000 and other protocol use.
The wifi disconnection watchdog that reboots the device after disconnection is now a LambdaConsumer of SystemStatus in SensESPApp instead of being hard-coded in the Networking class. Sure, the behavior is arguably still hard-coded but will be easier to modify in the future. This requires PR #365 to work.
Wifi state changes are now captured and propagated using event handlers. Due to underlying API differences, the implementation is platform-specific (different for ESP8266 and ESP32).
Wifi settings were not reset properly at least on …
> Non blocking wifi

- src/net/ws_client.cpp
Current minimum interval between SK delta messages is 100 ms. This change improves the maximum possible rate of deltas by decreasing the interval between calls to `send_delata()` to 5ms.
This  resolves #369
> Change min interval for sending deltas to 5 ms from 100 ms

- src/sensors/analog_input.h
- src/transforms/analogvoltage.h
- src/transforms/voltage_multiplier.h
- src/transforms/voltagedivider.h
Make it clear that AnalogVoltage is probably not needed in most cases.
> AnalogInput: update docs for this and related classes

- src/transforms/curveinterpolator.cpp
Entering and saving samples in the CurveInterpolator transform's web interface causes duplicates of the entered values to appear if the web interface is opened subsequent to the first save.  See issue #375 for details.
Fix consists of removing extraneous call to `jSamples.add(entry);`
> Fix duplication of CurveInterpolator samples

- library.json
I hadn't noticed that ReactESP version number was actually pinned down in library.json. This PR removes the version restriction.
> Don't pin down the ReactESP version number

- README.md
- docs/Add-ons.md
Add-on libraries are now listed on their own page with instructions on how to add your own.
> Create a separate page for add-on libraries

- Doxyfile
- library.json
- library.properties
To better differentiate between the stable releases and the development branch, this PR bumps the development branch version number to 1.0.4-alpha. This should not imply that the next release version is 1.0.4 -- it could be that, or 1.1.0, or 2.00, depending on the changes done during the development cycle.
> Bump master branch version number to 1.0.4-alpha

- src/sensors/bme280.cpp
Debug output of SensorID was in decimal, but should be in hexadecimal.
was `debugI("SensorID is: 0x%d", adafruit_bme280_->sensorID());`  
is now `debugI("SensorID is: 0x%T", adafruit_bme280_->sensorID());`
`%d` -> `%T`
> bme280.cpp decimal to hex

- library.json
- platformio.ini
- src/sensors/onewire_temperature.cpp
- src/sensors/onewire_temperature.h
DallasTemperature sensor implementation now correctly detects the read error codes. Under the hood, the 1-Wire library has been changed from the stale `PaulStoffregen/OneWire` to `pstolarz/OneWireNg`. This seems to fix all the read errors on ESP32 and works unchanged on ESP8266 too.
> 1-Wire error detection and library change

- src/net/networking.cpp
I noticed SensESP devices didn't have their hostnames announced in the DHCP address requests. This PR fixes the issue, allowing some routers (OpenWRT ones, in particular) to set local DNS addresses such as `my-sensesp.lan` for the devices, greatly helping with their discoverability.
> Set hostname before starting the network

- src/transforms/curveinterpolator.h
Not making the set_input method final will allow for overriding in subclasses to implement other functionality such as outputting the discrete value of the closest sample instead of interpolating.
> Remove final tag in order to enable overriding

- src/transforms/curveinterpolator.h
Not 100% sure if this is ok architecture wise: In order to override get_input in a subclass, I also need to be able to access samples since I still need to iterate over the samples in the implementation in my subclass. Please let me know if there is a more elegant way of doing this!
> Changed samples from private to protected

- README.md
To eliminate support "calls" when all of the libraries don't get downloaded.
> Add Git installation to README

- src/net/networking.cpp
When using this workaround, WiFi.localIP() returns 255.255.255.255 after a successful wifi connect and the signal k server can't be found with mdns.  
I tested that for the ESP8266 v2 with platform version Espressif 8266 v2.6.3
see here: https://github.com/espressif/arduino-esp32/issues/4732
> WiFi.localIP() returns broadcast address 255.255.255.255 when using workaround

- src/net/networking.cpp
After wifi is configured, the "Configure <hostname>" AP would still appear in a list of available AP's. This solves that.
> Prevent Configure <hostname> AP from showing

- src/system/pwm_output.cpp
Necessary due to a change in ESP8266/Arduino code. See SensESP Issue #424.
> Define PWMRANGE for ESP8266

- README.md
- examples/platformio.ini
- library.json
- platformio.ini
Note that this PR is against `master`, not `v2-dev`!
- Peg ReactESP to 1.x (to avoid breakage when ReactESP is updated to 2.0 with backwards-incompatible changes)
- Add instructions in README for pegging your own project SensESP dependency to 1.x
- Make a respective modification in the example platformio.ini file.
> Peg ReactESP and SensESP to 1.x

- docs/RELEASE_PROCESS.md
- examples/analog_input.cpp
- examples/chain_counter.cpp
- examples/fuel_level_sensor/fuel_level_sensor_example.cpp
- examples/hysteresis.cpp
- examples/lambda_transform.cpp
- examples/milone_level_sensor/milone_level_sensor.cpp
- examples/minimal_app.cpp
- examples/relay_control.cpp
- examples/rpm_counter.cpp
- examples/smart_switch/remote_switch_example.cpp
- examples/smart_switch/smart_switch_example.cpp
- examples/temperature_sender.cpp
- library.json
- platformio.ini
- scripts/update_autogen.sh
- src/sensesp.h
I released ReactESP v2 earlier today. This PR implements the required changes due to the updated API.
> ReactESP v2 changes

- src/sensors/ads1x15.h
One-character bugfixes are the best.
I didn't have suitable hardware at hand so I didn't actually test the change. Let's summon @RBerliner for that!
Fixes #473.
> ADS1115 output should be signed

- library.json
- platformio.ini
Also removed DNSSserver because it's not actually used. Go figure.
> Use the new preferred naming for dependencies

- platformio.ini
- src/net/ota.cpp
- src/net/ota.h
- src/sensesp_app.cpp
- src/sensesp_app.h
- src/sensesp_app_builder.h
Over-the-air updates are now enabled only if a password has been provided. This improves safety (a lot) and saves memory if OTA is not needed.
Fixes #453.
> Make OTA authentication mandatory

- examples/minimal_app.cpp
- src/net/networking.cpp
- src/net/networking.h
- src/sensesp_app.cpp
- src/sensesp_app.h
- src/sensesp_app_builder.h
WiFi Manager configuration access point is started if the WiFi configuration is not hardcoded and the device is unable to connect to the WiFi. Previously, this AP didn't have a password, allowing anyone nearby to hijack the device.
This PR adds a default password ("thisisfine") for WiFiManager. A builder method for changing the default password has also been implemented.
Fixes #454.
> Set a default password for the WiFi Manager configuration access point

- .github/workflows/test.yml
- examples/minimal_app.cpp
Accidentally broke the minimal_app example when adding the `get_hostname()` convenience method. Fixed that, and also added `examples/minimal_app.cpp` to the GitHub Actions run.
> Fix the minimal_app example

- examples/analog_input.cpp
Also update the comments to better document the calculation of the Linear multiplier and offset.
> Make analog_input example output a ratio instead of a percentage

- src/net/discovery.cpp
- src/sensesp_app.cpp
- src/sensesp_app.h
- src/sensesp_base_app.cpp
- src/sensesp_base_app.h
Some changes in hostname handling resulted in the MDNSDiscovery class not receiving the correct hostname, preventing the mDNS client from starting. Fixed now.
> Hostname handling fixes

- src/net/ws_client.cpp
- src/net/ws_client.h
- src/sensesp_app_builder.h
This was an optimization that, when turned off, would make the websocket connection logic bypass testing the authorization token on reconnects. Since this is very much a corner case and made the already hairy connection logic even more complex, I think it's better to remove it.
> Remove set_test_auth_on_each_connect builder member function

- .github/workflows/test.yml
- examples/async_repeat_sensor.cpp
- examples/repeat_sensor_analog_input.cpp
- src/sensors/sensor.h
RepeatSensor can be used to interface any generic arduino-esp32 compatible sensor library with SensESP. You initialize an upstream sensor interface object and set it up in `setup()`. Next, you define a callback function which will read and return a new value from the sensor interface. Finally, you instantiate `RepeatingSensor` and define the return type, repeat interval, and provide the callback function. The created `RepeatingSensor` object is a normal producer that can be connected to transforms and output objects as usual.
> Implement a RepeatSensor template class

- src/sensors/gps.cpp
- src/system/nmea_parser.cpp
- src/system/nmea_parser.h
GNGLL sentences are emitted when the fix comes from a combination of GPS
and GLONASS. Before this, the fix would be ignored.
SensESP's NMEA parser incorrectly treats southerly latitudes and
westerly longitudes as positive degrees, this change also fixes that.
> Add GNGLL parser, fix parsing of south and west coordinates

- src/signalk/signalk_position.cpp
Previously, SKOutputPosition seemed to be emitting the string "null".
This patch fixes it, at least for me. Maybe I was doing something wrong before. :)
> Fix SKOutputPosition emitting "null"

- src/sensesp/sensors/digital_input.h
The interrupt type was never set correctly because a crucial line had fallen off the constructor. Took quite some time to find that...
> DigitalInputCounter fix

- src/sensesp/sensors/digital_input.cpp
- src/sensesp/sensors/digital_input.h
Certain devices (e.g. reed switches) are very noisy when they actuate,
generating many interrupts per "event". In these cases, it is necessary to
ignore interrupts that occur very shortly after an initial interrupt.
This class is implemented as a slight specialization of DigitalInputCounter,
but the implementation is kept separate so that DigitalInputCounter may avoid
dynamic dispatch overhead (it needs to be able to run at high speed).
> add DigitalInputDebounceCounter counter

- docs/pages/tutorials/index.md
The tutorial index page should work as a generic index page for tutorials written by different contributors. For example, I intend to write some essential tutorials myself. Also, the index should provide some useful categorization of the content according to the topic and expected audience. It should not expect any linear ordering of the content: it should be possible to reorder the categories and content within the categories, even alphabetically or by date, if need be. Or by some other editorial priority order.
Thinking a bit more about it, the index page should not expect a linear order of the content at the top level. However, if you'd prefer keeping the beginner tutorials ordered in the index, we could have a "### Beginner Tutorial Series" (or whatever) to group all those tutorials …
> Updated the Tutorial index page

- src/sensesp/net/http_server.cpp
- src/sensesp/system/configurable.cpp
- src/sensesp/system/configurable.h
- src/sensesp/system/filesystem.cpp
- src/sensesp/system/hash.cpp
- src/sensesp/system/hash.h
SPIFFS has a maximum path length of 32 characters. To circumvent this, configuration file paths are hashed with SHA-1 and then base64 encoded.
~This change resets existing device configurations.~ There are checks in place to make it backwards-compatible.
Fixes #536.
> Hash the configuration file names

- Doxyfile
- src/sensesp/transforms/curveinterpolator.cpp
- src/sensesp/transforms/curveinterpolator.h
`CurveInterpolator` web UI was a bit clunky to use. I changed the editor into table format and added options to provide display names for the input and output sample values. With these tweaks, this is how it looks like:
> Curve interpolator UI improvements

- src/sensesp/system/local_debug.cpp
- src/sensesp/system/local_debug.h
A minor stylistic fix: `LocalDebug` wasn't wrapped in the `sensesp` namespace, which caused it to be displayed separately of the other items in the Doxygen docs. And maybe it should've been there, in the first place.
> Add LocalDebug to the sensesp namespace

- src/sensesp/signalk/signalk_position.cpp
- src/sensesp/signalk/signalk_position.h
- src/sensesp/signalk/signalk_time.cpp
- src/sensesp/types/position.h
I'm working on bringing the NMEA 0183 parser back to life. While the parser probably has no business in SensESP core, the data types could well be defined in SensESP itself to have a uniform representation of position and ENU vectors.
> Re-add Position and ENUVector structs

- docs/_config.yml
- docs/pages/additional_resources/index.md
A repo that never got published was linked in the "Additional resources" doc page. Removed now.
> Remove ina2xx link

- docs/pages/additional_resources/index.md
The additional_resources page has no children, so changed the has_children property to false.
> Fix the has_children property value

- src/sensesp/net/http_server.cpp
- src/sensesp/net/networking.h
- src/sensesp/net/ws_client.h
- src/sensesp/system/ui_output.cpp
- src/sensesp/system/ui_output.h
- src/sensesp_app.h
UIOutput objects were scattered around unrelated classes. They're now all collected to `SensESPApp`.
Additionally, the `ui_outputs` instance map was a global variable. That was changed into a static member variable of UIOutputBase.
Fixes #555.
> Collect UIOutput objects to SensESPApp

- src/sensesp/net/discovery.cpp
- src/sensesp/net/networking.cpp
- src/sensesp/net/ws_client.cpp
The previous SK server endpoint for testing the SK access token validity didn't work, resulting in the device no longer being able to connect to the server if the access token was invalidated on the server.
The validity checking endpoint at the server is not implemented, but I found out that the websocket stream endpoint works for this purpose, at least somewhat.
Some related SK server issues:
- SignalK/signalk-server#1396
- SignalK/signalk-server#1397
Fixes #552.
> Fix SK access token validity checking

- docs/pages/troubleshooting/index.md
The underlying issue was fixed in PR #559.
> Documentation: Remove obsolete token authorization troubleshooting section

- src/sensesp/types/position.h
In a momentary lapse of reason, I used #pragma once in one header file.
Given that #pragma once is nonstandard and has potentially unfixable
issues, let's revert back to using standard include guards.
> Replace #pragma once with an include guard

- library.json
- src/sensesp/controllers/system_status_controller.cpp
- src/sensesp/controllers/system_status_controller.h
- src/sensesp/net/http_server.cpp
- src/sensesp/net/http_server.h
- src/sensesp/net/networking.cpp
- src/sensesp/net/networking.h
- src/sensesp/net/wifi_state.h
- src/sensesp_app.cpp
SensESP WiFi connection logic was a bit fragile and unnecessarily complex. Different connecting code was used depending on whether the WiFI AP was hard-coded or configured via WiFi Manager, and also reconnecting in case of lost WiFi was unreliable. This PR attempts to address those issues.
Major changes:
- WiFi Manager configuration portal is only enabled if no previous configuration has been saved. Once SSID and password have been entered and verified to work, they will be used ever after (or at least until the device is reset).
- If the WiFi AP is not available or the connection is lost, the device will keep attempting to reconnect until a connection has been established. WiFi Manager never gets launched, and these reconnection attempts are non-blocking (so the device is still operating …
> WiFi connection logic improvements

- src/sensesp/system/local_debug.cpp
- src/sensesp/system/local_debug.h
> Fix the unbalanced namespace brackets when debugging is disabled

- platformio.ini
- src/sensesp/net/networking.cpp
- src/sensesp/net/networking.h
- src/sensesp/system/led_blinker.cpp
- src/sensesp/system/led_blinker.h
In some cases it's quite useful if the WiFiManager AP name can be set independently of the device hostname. This PR adds a simple setter method for defining a custom AP name.
> Allow setting of custom WiFiManager access point SSIDs

- platformio.ini
- src/sensesp/net/debug_output.h
- src/sensesp/net/http_server.cpp
- src/sensesp/net/networking.cpp
- src/sensesp/net/networking.h
- src/sensesp/system/configurable.cpp
- src/sensesp/system/hash.cpp
- src/sensesp/system/local_debug.cpp
- src/sensesp/system/local_debug.h
- src/sensesp/system/task_queue_producer.h
PlatformIO's espressif32 framework got updated from 3.5.0 to 4.1.0. The major change was that the Arduino ESP32 core got updated from 1.0.6 to 2.0.2. The change broke some APIs and exposed some bugs in SensESP. This PR fixes those.
> Fixes required by platformio/platformio-espressif32 v.4.1.0

- library.json
Shouldn't make much difference in practice, but makes the metadata better match reality.
> Limit the platform to espressif32 only

- src/sensesp/net/networking.cpp
Enabling the WiFi Access Point mode happens immediately, meaning that the internal WiFi status update callback is
called immediately. Not all startables have been called at this point, resulting in some consumers missing the update.
To fix the issue, emitting the WiFiStatus update is delayed until after the event loop has started.
> Delay the WiFi state update until all startables have been called

- src/sensesp/sensors/analog_reader.h
After upgrading to **_v2.4.1_** of SensESP and **_v4.2.0_** of platformio/esspressif32 I could finally compile for my **_Adafruit QT Py  ESP32-S2_** with only 1 error: setting the ADC width. The ADCs have changed on the newer ESP32 variants, the **_S2_** can have 13 bits of resolution. This fix should now cover the ESP32 and its variants.  Hope you have a successful compile!
> Fix for ESP32 variants  ADC width compile error

- src/sensesp/net/ws_client.cpp
When the SignalK server is auto-discovered through mDNS, the address and port are now saved into the `WSClient` instance so they can be later retrieved via the `get_configuration` method. Before this they were never stored, so calling the `get_configuration` function always returned an empty Json object
> Store auto-discovered SignalK server address & port

- src/sensesp/types/position.h
This teaches the ArduinoJson library how to deserialize Position type data like.
```json
{
"latitude": 39.482845,
"longitude": 2.352644,
"altitude": 0.1
}
```
This allows the use of the `SKValueListener` for this type of data like `navigation.position`.
> Add support to deserialize position type from Json

- src/sensesp/net/ws_client.cpp
Hello!!
my first PR on Github...
When a PutRequest is received by SensESP , a debuglog message " Untracked RequestID" and the value changed is not updated.
The code presented in PR is working fine for my application based on SmartSwitchcontroller.
> SKPutRequest  not updating values and untracked RequestId on Put

- examples/milone_level_sensor/milone_level_sensor.cpp
- src/sensesp/net/networking.cpp
- src/sensesp/system/task_queue_producer.h
According to e.g. https://www.intel.com/content/www/us/en/tech-tips-and-tricks/what-is-a-hotspot.html, a WiFi Hotspot is a physical location with internet access. So, we're always creating Access Points, not hotspots.
> Fix access point terminology

- .github/workflows/test.yml
- examples/raw_json.cpp
- src/sensesp/signalk/signalk_output.h
- src/sensesp/transforms/difference.cpp
- src/sensesp/transforms/integrator.h
- src/sensesp/transforms/lambda_transform.cpp
- src/sensesp/transforms/lambda_transform.h
Lambda transforms were storing the current output value in the configuration json object. This failed whenever the transform had a complex type that didn't have a standard Json serialization available.
This PR now stops storing the output value in the configuration object. That was a bad idea anyway...
Similar change has been made to `Difference` and `Integrator` transforms as well.
EDIT: Also added support for raw JSON SK output. If `String` objects are passed as input to `SKOutputRawJson`, the string contents will be inserted as-is as the value field of the respective paths.
> Lambda transform complex type support

- src/sensesp/net/ws_client.h
- src/sensesp/system/task_queue_producer.h
`set()` method now returns a boolean to indicate whether adding the value to the queue was successful or not.
Also, the default constructor now requires a pointer to `ReactESP` to indicate which task context is the consumer. An overloaded constructor without the pointer argument is provided for backwards compatibility.
> TaskQueueProducer changes

- .github/workflows/test.yml
- examples/manual_networking.cpp
- src/sensesp/net/networking.cpp
- src/sensesp/net/networking.h
- src/sensesp_app.cpp
The `Networking` object is no longer needed to produce the WiFi state. A separate `WiFiStateProducer has been created for the purpose. This allows for implementing network connection manually, as shown in the new `manual_networking.cpp` example.
> WiFi State output split away from Networking

- src/sensesp/net/ws_client.cpp
- src/sensesp/net/ws_client.h
The WSClient persistence logic now follows the rest of the codebase (I think...):
- If nothing is configured, mDNS is always used.
- If a server is hardcoded, it is used by default.
- If the server address is set through the config page, that address is used.
- If the server address is cleared through the config page, mDNS is used.
Fixes #634.
> Use mDNS always unless a server has been configured

- docs/pages/features/index.md
- library.json
- platformio.ini
- src/sensesp/system/base_button.h
- src/sensesp/system/button.cpp
- src/sensesp/system/button.h
- src/sensesp/system/minimal_button.h
- src/sensesp_app.cpp
- src/sensesp_app.h
- src/sensesp_app_builder.h
- src/sensesp_base_app.h
This PR implements a button handler for SensESP. The BOOT button on GPIO 0 detects the following events:
- Short press (less than 1 second): Restart the device
- Long press (more than 1 second): Reset the network settings
- Very long press (more than 5 seconds): Reset the device to factory settings
> Button Handler

- src/sensesp/transforms/threshold.cpp
- src/sensesp/transforms/threshold.h
Removed unused `out_range_` parameter from ThresholdTransform.
This PR fixes a bug that prevents the configuration for a FloatThreshold transform from being saved.
It also removes the unused `out_range_` variable from ThresholdTransform, which is always the opposite of `in_range_`.
> Fixed error when saving configuration for FloatThreshold

- library.json
- platformio.ini
ArduinoJson 7 has been just released. It breaks SensESP builds. Before changing the code to accommodate the new version, let's just peg the version dependency to 6.x.y.
> Peg ArduinoJson version to 6.x.y

- src/sensesp/types/position.cpp
- src/sensesp/types/position.h
In a momentary lapse of reason, I had defined some functions in a header file. That breaks if the header is included in more than one place. This PR moves the definitions to CPP files.
> Move function definitions from header to cpp file

- src/sensesp/sensors/constant_sensor.cpp
- src/sensesp/sensors/constant_sensor.h
Constant sensor config schema had always type "number". Thus, string constants could not be edited.
Also, fixes string deserialization as suggested by johandr on Discord. Fixes #682.
> Fix constant sensor configuration schema typing

- examples/freertos_tasks.cpp
- src/sensesp/controllers/system_status_controller.cpp
- src/sensesp/controllers/system_status_controller.h
- src/sensesp/signalk/signalk_delta_queue.h
- src/sensesp/signalk/signalk_ws_client.cpp
- src/sensesp/signalk/signalk_ws_client.h
- src/sensesp/system/led_blinker.h
- src/sensesp/system/system_status_led.cpp
- src/sensesp/system/system_status_led.h
- src/sensesp_app.cpp
- src/sensesp_app.h
Renamed the `WSClient` class and related filenames to `SKWSClient` for clarity.
> Breaking change: rename WSClient to SKWSClient

- src/sensesp/signalk/signalk_ws_client.cpp
- src/sensesp/signalk/signalk_ws_client.h
Updating to ArduinoJson 7 broke SKListener functionality because apparently the previous ArduinoJson copied JsonObjects by value and the new one does that by reference. Nothing wrong with that change in ArduinoJson, should've tested that.
Fixes Issue #688.
> Pass received Json objects always by value

- src/sensesp/transforms/curveinterpolator.cpp
The curve interpolator reacted strangely to values beyond the curve limits.
Values below the lower bound were linearly interpolated between the point 0,0 and the first curve point, values above the upper bound translated to 9999.99
It seems more graceful to simply continue the curve linearly above and below the lower and upper pair of points.  
If "hard limits" are desired, such as a tank cannot be less 0.0 empty or 1.0 full simply adding bounds points with the same value at the top and bottom of the list produces a flat line:
eg: 
(50,0)
(100,0)
(1000,1)
(1050,1) 
Willl produce a "flat" curve lowwr than 100 and above 1000,  effectively limiting the output.   Without the bound points, the linear curve extends above 1000 and below 100 without unpredictable results.
> Improved curve interpolator

- run
I had forgot to add my build script in the repo. The build script facilitates easy-to-use commands for managing and building the SensESP project itself, including building and updating the frontend sub-project.
> Add a build script

- examples/dual_thermocouple_sensors/max6675_signalk_n2k.cpp
- examples/dual_thermocouple_sensors/platformio.ini
Figure this would be welcome by some as it took me a bit to find the correct PGN to output.   Sorry you just recently merged my last update, but this is the speed I work at ;)
> Patch 2 - Add NMEA2000 Output of Exhaust Gas Temperature

- src/sensesp/sensors/constant_sensor.h
Removed `ConstantSensor::get_value` and made it emit the value immediately to allow value retrieval using `::get`. Also, Renamed `set_value()` to `set()` for consistency with the other classes.
> Rename ConstantSensor getters and setters

- src/sensesp/system/expiring_value.h
- src/sensesp/system/serial_number.h
`ExpiringValue` is a container that returns the contained value if its age is less that `max_age`. Otherwise, an expiration marker value is returned. This comes handy if you want to combine a large number of values into a single output while ensuring that the values are still current.
> Implement new ExpiringValue container class

- src/sensesp/net/networking.cpp
Earlier, it was set too late to be applied in DHCP client request.
> Set up hostname earlier in WiFi initialization

- src/sensesp/transforms/filter.h
A filter transform emits its input as is but only if the condition lambda function returns true.
> Implement a filter transform

- src/sensesp/system/local_debug.h
adding using directive in header files is not a good idea, with this PR
this code
```cpp
if(!config.containsKey(str)) {
debugE("N2kFluidLevelSender: Missing configuration key %s",
str.c_str());
return false;
}
```
will not require
```cpp
using namespace sensesp;`
```
in the include files
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#sf7-dont-write-using-namespace-at-global-scope-in-a-header-file
> to avoid using namespace at global scope

- src/sensesp/transforms/curveinterpolator.cpp
Applied Robin Szemeti's PR to dev-3 and fixed one related issue while at it.
> Curve interpolator fix v3

- src/sensesp.cpp
- src/sensesp.h
Calling `SensESPBaseApp::get_event_loop()` all the time grew old, so I added an `event_loop()` convenience function that just does the same.
> Add an event_loop() convenience function

- .github/workflows/test.yml
- src/sensesp/system/semaphore_value.h
`SemaphoreValue` is a new class that holds values like an `ObservableValue` but which uses a semaphore to flag value updates. If one task is writing to the `SemaphoreValue`, another class can `wait` on it and resume execution once a new value has been set.
> Implement a task synchronization consumable

- .github/workflows/test.yml
- src/sensesp/signalk/signalk_ws_client.h
- src/sensesp/system/saveable.cpp
- src/sensesp/system/semaphore_value.h
- src/sensesp/system/stream_producer.h
- src/sensesp/system/task_queue_producer.h
- src/sensesp/transforms/filter.h
TaskQueueProducer now uses std::queue internally instead of FreeRTOS task queues. The latter broke spectacularly when using them with C++ classes.
> Refactor TaskQueueProducer

- platformio.ini
- src/sensesp/controllers/smart_switch_controller.cpp
- src/sensesp/controllers/smart_switch_controller.h
- src/sensesp/net/http_server.cpp
- src/sensesp/net/http_server.h
- src/sensesp/net/networking.cpp
- src/sensesp/net/networking.h
- src/sensesp/net/web/app_command_handler.cpp
- src/sensesp/net/web/config_handler.cpp
- src/sensesp/sensors/analog_input.cpp
- src/sensesp/sensors/analog_input.h
- src/sensesp/sensors/system_info.h
- src/sensesp/signalk/signalk_emitter.h
- src/sensesp/signalk/signalk_output.h
- src/sensesp/system/base_button.h
- src/sensesp/system/filesystem.cpp
- src/sensesp/system/filesystem.h
- src/sensesp/system/system_status_led.cpp
- src/sensesp/system/system_status_led.h
- src/sensesp/system/valueproducer.h
- src/sensesp/ui/ui_button.cpp
- src/sensesp/ui/ui_button.h
- src/sensesp_app.cpp
- src/sensesp_app.h
- src/sensesp_app_builder.h
- src/sensesp_base_app.cpp
- src/sensesp_base_app.h
- test/system/test_config_item/config_item.cpp
- test/system/test_minimal_app/minimal_app.cpp
- test/system/test_serialization/serializable.cpp
At long last, I have implemented few rudimentary unit tests for SensESP. Not great, but at least it will be easier to add new ones in the future.
Also at long last, I have taken some steps to improve memory safety on SensESP. The codebase has been quite nonchalant about creating objects on the heap and not properly tracking them. This hasn't been an issue as long as the enclosing objects haven't been destroyed, but it's not a good practice, and with unit testing, it should be expected that the whole SensESP app will be torn down. I have now wrapped many internal heap objects in `shared_ptr` or `unique_ptr` and also added some destructors for select classes.
> Unit tests and memory safety

- README.md
- library.json
- platformio.ini
- src/sensesp/sensors/digital_input.h
- src/sensesp/sensors/system_info.cpp
- src/sensesp/sensors/system_info.h
- src/sensesp/system/semaphore_value.h
- src/sensesp/transforms/curveinterpolator.h
- src/sensesp/transforms/repeat.h
- src/sensesp_app.h
Provide data on the event loop performance.
> Improve instrumentation

- src/sensesp/net/http_server.h
- src/sensesp/net/networking.h
- src/sensesp/signalk/signalk_ws_client.h
- src/sensesp/ui/config_item.h
I have removed the default ConfigSchema template and provided overloads for built-in classes that have hardcoded UI implementations. ConfigItems should now work properly for template classes as well.
> Provide correct ConfigSchema for template classes

- platformio.ini
- src/sensesp.cpp
- src/sensesp.h
- src/sensesp/system/stream_producer.h
- src/sensesp/system/task_queue_producer.h
- src/sensesp_app.h
- src/sensesp_base_app.h
Strictly speaking, this is a breaking change, but since the impact should be quite limited and it removes a major use case of raw pointers, I'll just keep quiet and do it. Naughty me.
> Store EventLoop in a shared_ptr

- src/sensesp/transforms/debounce.cpp
- src/sensesp/transforms/debounce.h
> Fix Debounce configuration issues

- examples/minimal_app.cpp
- platformio.ini
- src/sensesp_app.h
Implemented a better minimal_app example.
> New minimal_app example

- src/sensesp/types/nullable.cpp
Such as engine_load_ in n2k_senders.h of
HALMET example firmware.
> Link fix for clients that use RepeatExpiring<int>

- examples/rpm_counter.cpp
- src/sensesp/sensors/digital_pcnt_input.cpp
- src/sensesp/sensors/digital_pcnt_input.h
Using the new PCNT API in ESP IDF 5.x [1], allocate a unit and channel,
configure edge actions and report back to client on a specified interval.
API surface similar to the previous interrupt-based DigitalInputCounter.
[1] https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/peripherals/pcnt.html
Fixes #805.
> Add a DigitalInputPcntCounter to count pulses using PCNT units

- src/sensesp/signalk/signalk_ws_client.cpp
- src/sensesp/system/task_queue_producer.h
The websocket task could barf if a particularly complex delta was to be sent. Also, task queue writer is simplified.
> Websocket fixes
