src/transforms/analogvoltage.h
src/transforms/debounce.cpp
src/transforms/debounce.h
src/transforms/interpolate.cpp
src/transforms/interpolate.h
src/transforms/temperatureinterpreter.cpp
src/transforms/temperatureinterpreter.h
src/transforms/voltagedividerR2.cpp
src/transforms/voltagedividerR2.h

New transforms needed to be made compatible with previous Configureable refactor.

Fix new transforms

---

src/sensesp_app.cpp
src/system/signalksource.h
src/transforms/difference.cpp
src/transforms/difference.h
src/transforms/frequency.cpp
src/transforms/frequency.h
src/transforms/gnss_position.cpp
src/transforms/gnss_position.h
src/transforms/integrator.cpp
src/transforms/integrator.h
src/transforms/interpolate.cpp
src/transforms/interpolate.h
src/transforms/linear.cpp
src/transforms/linear.h
src/transforms/moving_average.cpp
src/transforms/moving_average.h
src/transforms/passthrough.h
src/transforms/timestring.cpp
src/transforms/timestring.h
src/transforms/voltagedividerR2.cpp
src/transforms/voltagedividerR2.h

Rename method SignalKSource::as_json() to SignalKSource::as_signalK().
The main change here is in SignalKSource.h.  The other file changes are to support this change.

Signal k source as signal k

---

src/devices/onewire_temperature.cpp
src/devices/onewire_temperature.h
src/net/networking.cpp
src/net/ws_client.cpp
src/net/ws_client.h
src/sensesp_app.h
src/transforms/difference.cpp
src/transforms/frequency.cpp
src/transforms/gnss_position.cpp
src/transforms/integrator.cpp
src/transforms/interpolate.cpp
src/transforms/linear.cpp
src/transforms/moving_average.cpp
src/transforms/passthrough.h
src/transforms/timestring.cpp
src/transforms/transform.h
src/transforms/voltagedividerR2.cpp
src/wiring_helpers.cpp
src/wiring_helpers.h

A bunch of different things. Might be easier to review commit-by-commit.
- Some minor schema bugs fixed (loading `Frequency` configuration, matching expected used keys in `ws_config`, etc). 
- All schema are now saved in PROGMEM.
- `SymmetricTransform::connectFrom` fixed
- Removed the `connect_*to1` helpers and updated the wiring_helpers functions
Once you've checked this out, I'd like to bump the version up to 0.4.0 because the interface is somewhat incompatible after the `connect_*to1` changes.

Schema fixes

---

src/net/networking.cpp
src/net/ws_client.cpp
src/sensesp_app.cpp

Added several new debug() messages, and enhanced several more, all in the startup process. I changed one instance of the word "sensor" to "MCU", but if we decide to use "Device" instead of "MCU", I'll change it then.

docs: enhance debug msgs in the startup process

---

src/net/networking.cpp
src/net/ws_client.cpp
src/sensesp_app.cpp

After having all kinds of trouble getting these changes made in a branch called enhancedDebugMsgs, I deleted that branch and started over. The changes are exactly the same as those made and approved in that other branch.

Added and updated debug messages

---

src/signalk/signalk_output.h
src/signalk/signalk_position.cpp
src/signalk/signalk_position.h

fix: no signalk values in output 

---

examples/rpm_counter.cpp

Make the example very clear and educational to someone looking at a SensESP project for the first time. Add a lot of explanation to the comments. Delete the comment that showed how to wire it up the old way (before the refactor).

Update RPM example after refactoring

---

examples/rpm_counter.cpp

@joelkoz 's request that I didn't get in before I merged.

Minor comment change per jkoz request

---

src/sensors/gps.cpp
src/sensors/gps.h
src/transforms/angle_correction.cpp
src/transforms/angle_correction.h
src/transforms/linear.h
src/wiring_helpers.cpp
src/wiring_helpers.h

Implemented an angle correction transform (take an angle value and add a constant offset to it, wrapping the result value back into legal range).
Also fix GPSInput arguments and add optional reset_pin for forcing the GPS modules to reset.

feature: Angle correction transform

---

src/sensors/onewire_temperature.cpp

OK, I royally messed up the final touches to the previous PR. Here are the changes I failed to commit (because I didn't save the file, dammit)! Also a good reminder to actually review yourself the contents of the commit...

fix: Change OneWire log messages according to requests (this time for real)

---

examples/temperature_sender.cpp
src/transforms/curveinterpolator.h

Addresses issue #27 
Slight modification to the comment describing the CurverInterpolator transform, and a lot of additional comments in the example that uses it, temperature_sensor.cpp.

CurveInterpolator and temp_sensor example comments

---

src/net/networking.cpp
src/sensesp_app.cpp

Fix mDns discovery

---

src/net/http.cpp
src/net/ota.cpp
src/net/ws_client.cpp
src/sensesp_app.cpp
src/system/enable.h
src/system/nmea_parser.cpp
src/transforms/median.cpp
src/transforms/median.h

Fixed some simple compiler warnings

Remove compiler warnings

---

examples/OneWire_temperatures.cpp

This is the code running on my own boat.

Add OneWire Temperature example

---

src/net/web/setup.h

To be consistent with the definitions of "sensor" and "device".

Change 'sensor' to 'device'

---

src/sensors/analog_input.cpp
src/sensors/analog_input.h

I did this the same way it's done in DigitalInputCounter.

Add configurable read_delay to AnalogInput

---

src/sensesp_app.cpp
src/sensesp_app.h

To disable these "sensors" in your project, instantiate the SensESPApp like this: 
`sensesp_app = new SensESPApp(true);`.

Add ability to disable systemHz, etc.

---

src/transforms/analogvoltage.cpp
src/transforms/analogvoltage.h

Add setting for max voltage to AnalogVoltage

---

src/sensors/digital_input.cpp
src/transforms/voltagedividerR2.cpp

Add load_configuration() to constructors

---

examples/ina219_example.cpp
src/sensors/ina219.cpp
src/sensors/ina219.h

Requested by @DoubleDutch1962 on Slack. Issue #103.
I wrote it, sent files to him for testing. He says it works perfectly.

Add INA219 sensor and example

---

library.json

I tried building the ina219 example, but some library dependencies were missing. That is fixed by this pull request.
Btw. thanks for this great library!

Fix missing library dependencies.

---

examples/bme280_example.cpp
examples/bmp280_example.cpp
examples/sht31_example.cpp

Hi,
I have build succesfully my first ESP32 with BMP280.
Here is example, how to use this sensor with SensESP
Fair wind
free-x

Add example for BMP280 Sensor

---

src/net/ws_client.cpp
src/net/ws_client.h

Added ws connection check to loop function and reordered connection check in send delta.
This makes the ReactApp to SensApp behavior not guru on you. IT also allows access to the web configuration while it is trying as well.

Added connection check to ::loop() function

---

src/net/ws_client.cpp
src/net/ws_client.h
src/sensesp_app.cpp
src/sensesp_app.h
src/sensesp_app_builder.h

SensESPAppBuilder setters didn't work properly. Additionally, the meta-sensors (freemem, ipaddr, uptime etc) were disabled by default, which changed the default behavior.
Also some other minor changes.

SensESPAppBuilder fixes

---

src/net/networking.cpp

Display IP address of ESP after connecting to wifi

---

src/sensors/bme280.cpp

Remove pause in program if BME280 sensor not found

---

src/sensesp_app.cpp

Smal tweak to make the message visible in terminal

Add new line before message

---

examples/thermocouple_temperature_sensor/max31856_thermocouple_example.cpp
examples/ultrasonic_level_sensor/ultrasonic_DVP_example.cpp

I had missed one example and missed to delete some rows.
Also tweaked the "Serial debug enabled" with new line so it is visible in terminal output.

Fix debug function

---

examples/hysteresis.cpp
src/transforms/hysteresis.h

Work in progress:
- has extra commits from existing PRs
- No documentation

Hysteresis transform implementation using LambdaTransform

---

.github/workflows/test.yml
examples/fuel_flow_meter.cpp
examples/gps_compass.cpp
examples/milone_level_sensor/milone_level_sensor.cpp
examples/onewire_temperature/onewire_temperature_example.cpp
examples/rpm_counter.cpp

Added GitHub Actions flow to automatically build example files
Fixed some examples to work with all specified boards in platform.ini
I'm not sure all pin numbers are suitable for ESP32

Actions workflow in github to build examples

---

examples/ads1x15_volt_meter.cpp
examples/analog_input.cpp
examples/fuel_level_sensor/fuel_level_sensor_example.cpp
examples/hysteresis.cpp
examples/ina219_example.cpp
examples/lambda_transform.cpp
examples/onewire_temperature/onewire_temperature_example.cpp
examples/relay_control.cpp
examples/rpm_counter.cpp
examples/sht31_example.cpp
examples/temperature_sender.cpp
examples/thermocouple_temperature_sensor/max31856_thermocouple_example.cpp
examples/ultrasonic_level_sensor/ultrasonic_dvp_example.cpp

There are some paths that not exists in documentation, I have not touched those.
Fixes #212

SK Paths are now valid

---

src/net/ws_client.cpp
src/signalk/signalk_value_listener.h

Hi Guys,
as promised, I've fixed SKListener and serialization of subscriptions in WSClient.
I've tested it on my ESP32DEV and it works!
Thanks

Fixed SKListener subscriptions

---

examples/lambda_transform.cpp

Input Type and Output Type were reversed in the comment.

Fix comment

---

examples/platformio.ini
platformio.ini
src/sensesp_app.cpp
src/sensesp_app.h
src/sensesp_app_builder.h
src/system/led_blinker.cpp
src/system/led_blinker.h
src/system/led_controller.cpp
src/system/led_controller.h

This is a preview of new led controller and blinker implementation. There's now a dedicated LedController object that consumes notifications from Networking and WSClient objects and changes the led blinking pattern accordingly. 
Everything is hardcoded at the moment. Some refactoring should be done to allow changing or modifying the LedController object as well as connecting new consumers to the Networking and WSClient objects.
This is basically ready but waiting for PR#237 to be merged. This PR currently duplicates the commits of that PR -- if you want to look at the changes, they're all in the last commit.

New blinkenlights

---

src/sensesp_app.cpp
src/sensesp_app.h
src/sensesp_app_builder.h
src/system/led_controller.h
src/system/visual_controller.h
src/system/visual_output_controller.h

Generalized `LedController` into a `VisualOutputController` that can be used to implement e.g. display output. It's also possible to provide the controllers via `SensESPAppBuilder`.

Blinkenlights controller

---

.clang-format
src/controllers/visual_output_controller.h
src/net/ws_client.h
src/sensesp_app.h
src/sensesp_app_builder.h
src/system/led_controller.h
src/system/valueproducer.h
src/system/visual_output_controller.h

Some modifications were required to make the VisualOutputController properly usable in external libraries

VisualOutputController fixes

---

src/system/lambda_consumer.h

I'll add the example that's referred to in the comments in a separate PR. (Waiting on a couple other PR's to be able to complete the example.)

Initial submission of lambda_consumer

---

examples/bme280_example.cpp
examples/bmp280_example.cpp
examples/fx8700_heading_example.cpp
examples/ina219_example.cpp
examples/sht31_example.cpp
src/sensors/bme280.h
src/sensors/bmp280.h
src/sensors/ina219.h
src/sensors/orientation_9dof_input.h
src/sensors/sht31.h

Fix enums in Sensors to avoid namespace conflicts.

---

src/net/ws_client.cpp
src/net/ws_client.h
src/sensesp_app.h
src/signalk/signalk_put_request.cpp
src/signalk/signalk_put_request.h

Allows control of Signal K devices that respond to PUT requests defined in the SignalK specification at https://signalk.org/specification/1.5.0/doc/put.html

SKPutRequest transform

---

Doxyfile
docs/RELEASE_PROCESS.md

Some improvements to our Doxygen config.

Create more interactive Doxygen documents

---

src/transforms/transform.h
src/wiring_helpers.cpp

Rename Transform::connectFrom to connect_from

---

src/transforms/debounce.cpp
src/transforms/debounce.h

Remove a few lines that were previously just commented out, by request.

Remove DebounceTemplate<String>

---

src/transforms/integrator.h

Solves the compiler warning in Issue #316.

Fix compiler warning in Integrator

---

src/signalk/signalk_output.h

SKOutput did not load its configuration on startup. This PR is a fix for #325

Fix #325 SKOutput load configuration

---

src/sensors/sensor.cpp
src/sensors/sensor.h
src/sensors/sht31.cpp
src/sensors/sht31.h
src/sensors/system_info.cpp
src/sensors/system_info.h
src/sensors/ultrasonic_distance.cpp
src/sensors/ultrasonic_distance.h

Continuing the cleanup:
- Sensor base class
- SHT31
- SystemInfo
- Ultrasonic
Ready to review. (Just 3 more sensors to go!)

Part 2: Doxygen; data member names; remove "value" from Config UI; (for many Sensors) 

---

src/sensors/ads1x15.cpp
src/sensors/ads1x15.h
src/sensors/analog_input.h
src/sensors/analog_reader.h
src/transforms/analogvoltage.cpp
src/transforms/analogvoltage.h

Address Doxygen issues noted when Version 1.0.0 was released.
Other MINOR fixes in code noticed while fixing Doxygen.
This addresses these issues in several files. I still have a lot more to go, but I don't want to have too many in one PR, so this is it for now. I'll keep going in other PR's when I have time.

Various files: Fix or add Doxygen comments; minor clean-up

---

src/sensors/ads1x15.cpp
src/sensors/analog_input.cpp
src/sensors/max31856_thermocouple.cpp
src/sensors/max31856_thermocouple.h
src/sensors/orientation_9dof_input.cpp
src/sensors/orientation_9dof_input.h
src/transforms/analogvoltage.cpp
src/transforms/analogvoltage.h
src/transforms/angle_correction.cpp

The last of the Sensors cleanup.
- orientation_9dof
- max31856
- analog_voltage
- angle_correction (a transform)

Part 3: All sensors: Doxygen comments, data member names, remove value

---

src/transforms/angle_correction.cpp
src/transforms/angle_correction.h
src/transforms/change_filter.cpp
src/transforms/change_filter.h
src/transforms/click_type.cpp
src/transforms/click_type.h
src/transforms/frequency.cpp
src/transforms/frequency.h
src/transforms/linear.cpp
src/transforms/linear.h
src/transforms/median.cpp
src/transforms/median.h
src/transforms/moving_average.cpp
src/transforms/moving_average.h
src/transforms/press_repeater.cpp
src/transforms/press_repeater.h

Several transforms are cleaned up in this PR:
- AngleCorrection
- ChangeFilter
- ClickType
- Frequency
- Linear
- Median
- MovingAverage
- PressRepeater
Several more to do in another PR.

Clean up Transforms: Doxygen, data member names, remove value from Config UI, etc.

---

src/transforms/repeat_report.cpp
src/transforms/repeat_report.h
src/transforms/threshold.cpp
src/transforms/threshold.h
src/transforms/transform.cpp
src/transforms/transform.h
src/transforms/truth_text.cpp
src/transforms/truth_text.h
src/transforms/typecast.h
src/transforms/voltage_multiplier.cpp
src/transforms/voltage_multiplier.h
src/transforms/voltagedivider.cpp
src/transforms/voltagedivider.h

More cleanup of transforms:
- RepeatReport
- Threshold
- TruthToText
- Typecast
- VoltageDivider
- VoltageMultiplier
Ready for review.

Part 2 of Transform Cleanup (Doxygen, data member names, remove "value" from config, etc.)

---

examples/thermocouple_temperature_sensor/max31856_thermocouple_example.cpp
src/sensors/max31856_thermocouple.cpp
src/sensors/max31856_thermocouple.h

- Change the conversion mode to ONESHOT.
- Add a second constructor, per @mairas request.
- Remove potential endless loop with begin().
- Add a constructor without the obsolete data ready pin.
- Update the example.

MAX31856 enhancements

---

src/sensors/sht31.cpp

fix: output SHT31 humidity as ratio, not percent

---

src/sensors/bme280.cpp

Fix: BME280 humidity output as ratio

---

src/net/ws_client.cpp
src/net/ws_client.h

Two minor cleanups: first, token validity is now tested on a URL that doesn't return a ton of data. Second, a bit of logic cleanup that should have no functional changes.

WSClient cleanups

---

README.md
examples/multiple_sensors_example.cpp

Several people have asked on Slack about using more than one sensor in a single main.cpp. This should address that.

Multiple sensor example

---

examples/bme280_example.cpp
src/transforms/dew_point.cpp
src/transforms/dew_point.h
src/transforms/heat_index.cpp
src/transforms/heat_index.h

Heat index transform added.
Example of transform added in BME280_example (and I changed a key from `inside.engineroom` to `outside`)

Heat_index transform added

---

docs/Add-ons.md

Add the SH-ESP32 temperature sensing tutorial to the list of related projects

SH-ESP32 temperature sensing tutorial 

---

library.json

Fixes #403.
Fixes #244.
Fixes #216.

Remove unnecessary AHRS dependency

---

src/transforms/enable.h

Implement a simple `Enable` transform that allows the users to enable/disable signal propagation over the web UI.

Enable transform

---

src/net/networking.cpp

Fixes #428.
Refer also esp8266/Arduino#7902 and alanswx/ESPAsyncWiFiManager#83

WiFi Credential Persistence Across Reboot

---

examples/analog_input.cpp
examples/chain_counter.cpp
examples/hysteresis.cpp
examples/lambda_transform.cpp
examples/milone_level_sensor/milone_level_sensor.cpp
examples/rpm_counter.cpp
src/sensesp_base_app_builder.h
src/sensors/analog_input.cpp
src/sensors/analog_input.h
src/sensors/digital_input.cpp
src/sensors/digital_input.h
src/sensors/sensor.cpp
src/sensors/sensor.h
src/transforms/frequency.h

DigitalInput classes were a bit messy; the base class took arguments which weren't used by all children, and the documentation was at places digressing and assuming some specific use cases.
Also, `Sensor` is now a proper template class which simplifies the code a bit.
Finally, some unrelated chore fixes included...

Digital input refactoring

---

examples/minimal_app.cpp
src/sensesp_app.cpp
src/sensesp_app.h
src/sensesp_app_builder.h
src/sensesp_base_app.cpp
src/sensesp_base_app.h
src/sensesp_minimal_app_builder.h
src/sensors/system_info.cpp
src/sensors/system_info.h

System info sensors are reimplemented and the builder methods are added to `SensESPAppBuilder`.

System info sensors

---

examples/analog_input.cpp
examples/chain_counter.cpp
examples/hysteresis.cpp
examples/lambda_transform.cpp
examples/milone_level_sensor/milone_level_sensor.cpp
examples/rpm_counter.cpp
examples/temperature_sender.cpp
library.json
platformio.ini
src/net/discovery.cpp
src/net/networking.cpp
src/net/networking.h
src/net/ws_client.cpp
src/sensesp.h
src/sensors/analog_input.h
src/sensors/analog_reader.h
src/sensors/system_info.cpp
src/system/configurable.cpp
src/system/filesystem.cpp
src/system/led_blinker.cpp
src/system/pwm_output.cpp
src/system/pwm_output.h
src/system/uuid.cpp

Remove ESP8266 specific code paths, comments and dependencies.
Fixes #457.

Remove ESP8266 support

---

examples/minimal_app.cpp
src/net/debug_output.cpp
src/net/discovery.cpp
src/net/http_server.cpp
src/net/networking.cpp
src/net/ws_client.cpp
src/sensesp_app.cpp
src/sensesp_base_app.cpp
src/sensesp_base_app.h
src/signalk/signalk_delta_queue.cpp

Implement a get_hostname() convenience method

---

examples/analog_input.cpp

Also rewrite the comments to better explain how to calculate the Linear multiplier and offset.

Fix analog_input example: make the output a ratio, not a percentage

---

src/system/valueconsumer.h
src/transforms/curveinterpolator.h
src/transforms/transform.h

Some deprecated methods were still lurking around. Nuked them.

Remove deprecated methods

---

examples/async_repeat_sensor.cpp
examples/repeat_sensor_analog_input.cpp

I made a mess by merging PR #493 too soon; the examples had all kinds of problems that have been fixed in this PR. Hopefully.

Fix RepeatSensor example variable names and comments

---

examples/platformio.ini

And the reference to esp-wrover-kit.

Remove ESP8266 references

---

docs/pages/concepts/index.md
docs/pages/internals/index.md

I accidentally merged PR #513 without pushing the requested changes. This PR fixes that.

Implement changes requested in PR #513 review

---

src/sensors/digital_input.cpp
src/sensors/digital_input.h

This change is similar to https://github.com/SignalK/SensESP/pull/510, just back-ported to the V1 API. I've tested this one and it works quite nicely.

Add debounce counter v1

---

docs/Add-ons.md

Fix the v1 documentation link to the INA2xx library as reported by Greg Young on Slack.

Update v1 Add-ons.md

---

src/sensesp/net/http_server.cpp

The "info" json object is generated dynamically in `HTTPServer::handle_info`. Previously, its required size was estimated only from the number of configurables, omitting the ui_outputs and ui_buttons. This PR fixes that, allowing all UIOutputs to display properly.

Allocate enough memory for the "info" json object

---

examples/temperature_sender.cpp

The code was updated per issue #638.
The original code did not transform the decimal bit into voltage, so the calc did not correctly calculate.  associated descriptions/explanations were also updated.

Correction to the calculation per issue #638

---

README.md
docs/pages/troubleshooting/index.md

doc: fix Slack invite links

---

src/sensesp/signalk/signalk_listener.cpp
src/sensesp/signalk/signalk_listener.h
src/sensesp/signalk/signalk_value_listener.h

Please review, I am not an expert on C++

added signalk_listener config option

---

examples/dual_thermocouple_sensors/max6675_signalk.cpp
examples/dual_thermocouple_sensors/platformio.ini
examples/thermocouple_max6675

Wanted to provide sample code for reading 2 thermocouples for exhaust (gas) temperature measurement.

Add thermocouple_max6675 example

---

src/sensesp/system/stream_producer.h
src/sensesp/system/task_queue_producer.h

Implement stream producers that produce values either when a stream has any input available (`StreamCharProducer`) or when a stream has a whole new line available (`StreamLineProducer`).

Stream producers

---

src/sensesp/transforms/repeat.h
src/sensesp/types/nullable.cpp
src/sensesp/types/nullable.h

RepeatExpiring and friends were actually broken earlier. Should be fixed now.

Fix Repeat template classes

---

.github/workflows/test.yml
src/sensesp/transforms/threshold.cpp
src/sensesp/transforms/threshold.h

I had removed the Threshold transform during v3 development, but apparently it was used by many people. Let's bring it back!

Restore Threshold transform

---

examples/smart_switch/remote_switch_example.cpp
src/sensesp/controllers/smart_switch_controller.h
src/sensesp/system/pwm_output.cpp
src/sensesp/system/pwm_output.h
src/sensesp/system/rgb_led.cpp
src/sensesp/system/rgb_led.h

It now allows adjustment of PWM frequency and channel resolution. The interface changed slightly; no need to mess with PWM channels manually.

Refactor PWMOutput
